// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'newproject': string;
  'projects': string;
  'tile': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
