// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'tile': string;
  'tooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
