// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'butt': string;
  'link': string;
  'logo': string;
  'modal': string;
  'navbar': string;
  'photo': string;
  'trigger': string;
  'unhide': string;
}
export const cssExports: CssExports;
export default cssExports;
