// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'finish': string;
  'middle': string;
  'single': string;
  'start': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
