// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'calendar': string;
  'header': string;
  'noselect': string;
}
export const cssExports: CssExports;
export default cssExports;
